version: '3'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27020:27017"
    volumes:
      - ./build/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=order